import json
import logging
import concurrent.futures
import time
from threading import Thread

import wx
import os
from cron_descriptor import ExpressionDescriptor

from core.cron.cron import Cron
from core.definition.SeleniumIDERecordingConverter import SeleniumIDERecordingConverter
from core.execution import Execution
from core.executor import Executor
from core.loop import Loop
from core.pipeline import Pipeline
from core.processor import Processor
from core.task import Task
from decorators.decorators import reload_log_after
from mvp.model.PETPModel import PETPModel
from mvp.presenter.PETPInteractor import PETPInteractor
from mvp.presenter.event.PETPEvent import PETPEvent
from mvp.view.common.InputDialog import InputDialog
from mvp.view.common.SearchableComboBox import SearchableComboBox
from mvp.view.common.SearchableGridChoiceEditor import SearchableGridChoiceEditor
from mvp.view.sub.PETP_LINE_CHARTView import PETP_LINE_CHARTView
from mvp.view.sub.PETP_PIE_CHARTView import PETP_PIE_CHARTView
from mvp.view.sub.PETP_BAR_CHARTView import PETP_BAR_CHARTView
from mvp.view.PETPView import PETPView
from utils.DateUtil import DateUtil
from utils.OSUtils import OSUtils
from utils.CodeExplainerUtil import CodeExplainerUtil


class PETPPresenter():
    CRON_INVALID: str = "Invalid CRON"

    cron: Cron
    execution: Execution
    executors: list = []
    pipeline: Pipeline
    converter: SeleniumIDERecordingConverter

    available_processors: list = []
    available_executions: list = []

    current_selected_row: int = -1
    _pgrid_bound_row: int = -1  # row the property grid is currently showing
    is_log_content_focused: bool = False
    single_page: str = "petp"
    logger_thread = None
    keep_running = True

    def __init__(self, model: PETPModel, view: PETPView, interactor: PETPInteractor):

        self.m = model
        self.v = view
        self.i = interactor

        # Incremental log loading state
        self._log_last_pos = 0
        self._log_last_update = 0.0
        self._log_throttle_sec = 0.3
        self._log_pending = False

        # Upgrade choosers BEFORE the interactor binds events, so all
        self._upgrade_chooser(attr="executionChooser", tooltip="Select or search Execution (type to filter)", )
        self._upgrade_chooser(attr="pipelineChooser", tooltip="Select or search Pipeline (type to filter)", )

        self.i.install(self, view)

        logging.info('Init PETPPresenter')

        self._load_available_executions()
        self._load_available_pipelines()

        self._init_taskgrid_choice_editor()
        self._init_executiongrid_choice_editor()
        self._init_cron()
        self._init_property_grid()

        self._load_config()

    def _upgrade_chooser(self, attr: str, tooltip: str = ""):
        """
        Replace the plain wx.ComboBox generated by wxGlade (identified by *attr*
        on the view) with a SearchableComboBox – without touching PETPView.py.

        Must be called BEFORE self.i.install() so event bindings in PETPInteractor
        automatically target the new widget (they read self.v.<attr> at bind time).
        """
        old = getattr(self.v, attr, None)  # type: wx.ComboBox | None
        if old is None or isinstance(old, SearchableComboBox):
            return  # already upgraded or attribute missing

        parent = old.GetParent()
        sizer = old.GetContainingSizer()

        new = SearchableComboBox(
            parent,
            wx.ID_ANY,
            choices=[],
            style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER,
        )
        new.SetMinSize(old.GetMinSize())
        if tooltip:
            new.SetToolTip(tooltip)

        # Swap the widget inside the existing sizer so layout is preserved.
        if sizer:
            sizer.Replace(old, new)
            sizer.Layout()

        old.Destroy()
        setattr(self.v, attr, new)
        logging.debug(f"Upgraded {attr} → SearchableComboBox")

    def _handle_execute_on_startup(self):
        if self.m.execute_on_startup:
            logging.info(f"execute on startup is enabled, will run execution: {self.m.last_run}")
            self.on_run_execution()

    def _load_config(self):
        # load_executeonstartup
        if self.m.execute_on_startup is not None:
            self.v.checkbox_executeonstartup.SetValue(self.m.execute_on_startup)

        # load_log_level
        if self.m.log_level is not None:
            self.v.logLevelChooser.SetValue(self.m.log_level)

        # load http_port, as part of title
        self.v.SetTitle(self.v.GetTitle() + " [ " + str(self.m.http_port) + " ]")

        # load_last_run
        if self.m.last_run is not None:
            logging.info("loading last run: " + self.m.last_run)
            self.v.executionChooser.SetValue(self.m.last_run)
            self.on_task_execution_changed()

    def _init_property_grid(self):
        self.v.taskProperty.AddPage(self.single_page)
        self._append_property_category(self.v.taskProperty, "Input Editor")

        self.v.loopProperty.AddPage(self.single_page)
        self._append_property_category(self.v.loopProperty, "Loop Editor")

    def _append_property_category(self, propgrid_manager, category_name):
        page = propgrid_manager.GetPage(self.single_page)
        page.Append(wx.propgrid.PropertyCategory(category_name))

    def _reset_task_pgrid(self, task_number=0):
        self.v.taskProperty.ClearPage(self.v.taskProperty.GetPageByName(self.single_page))
        self._append_property_category(self.v.taskProperty,
                                       "Input Editor of T" + str(
                                           task_number) if task_number > 0 else "Input Editor")

    def _reset_loop_pgrid(self):
        self.v.loopProperty.ClearPage(self.v.loopProperty.GetPageByName(self.single_page))
        self._append_property_category(self.v.loopProperty, "Loop Editor")

    def on_grid_cell_right_click(self, evt):
        evt.Skip()

        self.selected_row_2_copied_paste = evt.Row

        if not hasattr(self, "popup_id_copy"):
            self.popup_id_copy = wx.NewId()
            self.popup_id_paste = wx.NewId()

        menu = wx.Menu()

        item_copy = wx.MenuItem(menu, self.popup_id_copy, "Copy")
        self.v.Bind(wx.EVT_MENU, self._on_grid_row_copy, item_copy)

        item_paste = wx.MenuItem(menu, self.popup_id_paste, "Paste")
        self.v.Bind(wx.EVT_MENU, self._on_grid_row_paste, item_paste)

        menu.Append(item_copy)
        menu.Append(item_paste)

        self.v.PopupMenu(menu)

        menu.Destroy()

    @reload_log_after
    def _on_grid_row_copy(self, evt):
        self.row_copied = [
            self.v.taskGrid.GetCellValue(self.selected_row_2_copied_paste, 0),
            self.v.taskGrid.GetCellValue(self.selected_row_2_copied_paste, 1)
        ]
        logging.debug("selected_row_copied" + str(self.row_copied))

    def _on_grid_row_paste(self, evt):
        self.v.taskGrid.SetCellValue(self.selected_row_2_copied_paste, 0, self.row_copied[0])
        self.v.taskGrid.SetCellValue(self.selected_row_2_copied_paste, 1, self.row_copied[1])

    def _init_cron(self):
        self.cron = Cron(self.v)

    def _load_available_executions(self):
        self.available_executions = Execution.get_available_executions()
        self._execution_all_items = list(self.available_executions)
        self.v.executionChooser.AppendItems(self.available_executions)
        # Mark tool executions so they display with a 🔧 prefix
        tool_names = Execution.get_tool_execution_names()
        if tool_names:
            self.v.executionChooser.set_tool_names(tool_names)

    def _load_available_pipelines(self):
        self.v.pipelineChooser.AppendItems(Pipeline.get_available_pipelines())

    def _init_executiongrid_choice_editor(self):
        self.available_executions = Execution.get_available_executions()
        execution_grid = self.v.executionGrid
        for row in range(execution_grid.GetNumberRows()):
            self._bind_grid_cell_choice_editor(row, execution_grid, self.available_executions)

    def _init_taskgrid_choice_editor(self):
        self.available_processors = Processor.get_processors()
        task_grid = self.v.taskGrid
        for row in range(task_grid.GetNumberRows()):
            self._bind_grid_cell_choice_editor(row, task_grid, self.available_processors)

    def on_add_loop(self):
        loop_code = 'loop-' + DateUtil.get_now_in_str()
        loop_tpl = Loop.tpl()
        page = self.v.loopProperty.GetPage(self.single_page)
        self._append_or_update_property_to_page(loop_code, loop_tpl, page)
        page.FitColumns()

    def on_del_loop(self):
        page = self.v.loopProperty.GetPage(self.single_page)
        self._delete_selected_property_from_page(page)

    def on_convert_get_deep_data_4loop(self):
        """ NOT IMPLEMENTED YET """
        pass

    def on_convert_get_data_4loop(self):
        """ NOT IMPLEMENTED YET """
        pass

    def on_close_window(self):
        self.logger_thread = None
        self.keep_running = False
        self.v.tbicon.Destroy()

    def on_notebook_page_changed(self, evt):
        # switch notebook tab from execution to pipeline
        if evt.Selection == 1:
            self._init_executiongrid_choice_editor()

    @reload_log_after
    def on_log_level_changed(self):
        combo = self.v.logLevelChooser
        log_level = combo.GetValue()

        # record log_level
        if self.m.log_level != combo.GetValue():
            self.m.log_level = combo.GetValue()
            self.m.set_config('log_level', self.m.log_level)

        logging.getLogger().setLevel(logging.getLevelName(log_level))
        getattr(logging, log_level.lower())('Set log level to <' + log_level + '> successfully.')

    @reload_log_after
    def on_execution_pipeline_changed(self):
        combo = self.v.pipelineChooser
        grid = self.v.executionGrid
        grid.ClearGrid()

        self.pipeline = Pipeline.get_pipeline(combo.GetValue())
        if self.pipeline is None:
            return
        else:
            current_number_rows = grid.GetNumberRows()
            execution_number = len(self.pipeline.list)

            self.v.asCronChecbox.SetValue(self.pipeline.cronEnabled)
            self.v.cronInput.SetValue(self.pipeline.cronExp)
            self._update_cron_setting(self.pipeline.cronEnabled)

            if execution_number > current_number_rows:
                for _ in range(execution_number - current_number_rows):
                    self._insert_row(grid, self.available_executions)

            for idx, itm in enumerate(self.pipeline.list):
                grid.SetCellValue(idx, 0, itm['execution'])
                if 'input' in itm:
                    grid.SetCellValue(idx, 1, itm['input'])

    def _reset_property_grid(self):
        self._reset_task_pgrid()
        self.v.avaibleProperties.Clear()

    @reload_log_after
    def on_task_execution_changed(self):
        self._reset_property_grid()
        combo = self.v.executionChooser
        grid = self.v.taskGrid
        grid.ClearGrid()
        execution_desc = self.v.execution_desc
        cb_astool = self.v.cb_astool
        execution_desc.Clear()

        self.execution = Execution.get_execution(combo.GetValue())
        if self.execution is None:
            return
        else:
            current_number_rows = grid.GetNumberRows()
            task_number = len(self.execution.list)

            if task_number > current_number_rows:
                for _ in range(task_number - current_number_rows):
                    self._insert_row(grid, self.available_processors)

            for idx, itm in enumerate(self.execution.list):
                grid.SetCellValue(idx, 0, itm.type)
                if (hasattr(itm, 'input')):
                    grid.SetCellValue(idx, 1, itm.input)

            self._reset_loop_pgrid()
            if not hasattr(self.execution, 'loops'):
                return

            if len(self.execution.loops) > 0:
                for idx, itm in enumerate(self.execution.loops):
                    self._append_or_update_property_to_page(
                        itm.loop_code,
                        itm.loop_attributes,
                        self.v.loopProperty.GetPage(self.single_page)
                    )

            if hasattr(self.execution, 'mcp_desc') and self.execution.mcp_desc is not None:
                execution_desc.SetValue(self.execution.mcp_desc)

            if hasattr(self.execution, 'astool') and self.execution.astool is not None:
                cb_astool.SetValue(self.execution.astool)
            else:
                cb_astool.SetValue(False)

    @reload_log_after
    def on_execution_search(self, evt):
        # Use GetValue() which strips the tool-icon prefix, instead of raw evt.String
        combo = self.v.executionChooser
        search_value = combo.GetValue()
        search_text = search_value.lower()
        all_executions = Execution.get_available_executions()

        if search_value in all_executions:
            self._reload_executions(all_executions, search_value)
            combo.Dismiss()
            return

        filtered_executions = [exec_name for exec_name in all_executions if search_text in exec_name.lower()]
        exact_match = len(filtered_executions) == 1 and search_text == filtered_executions[0].lower()

        if exact_match:
            self._reload_executions(all_executions, filtered_executions[0])
            combo.Dismiss()
        else:
            self._reload_executions(filtered_executions or all_executions, search_value)
            combo.Popup()

    def _reload_executions(self, items, value):
        self.v.executionChooser.Reload(items, value)

    def _save_execcution(self, name):
        grid = self.v.taskGrid
        loop_property = self.v.loopProperty

        # prepare tasks
        tasks = []
        for row in range(0, grid.GetNumberRows()):
            t_type = grid.GetCellValue(row, 0)
            t_input = grid.GetCellValue(row, 1)
            if len(t_type) == 0 and len(t_input) == 0:
                break
            logging.info(f'{t_type} -> {t_input}')

            tasks.append(Task(t_type, t_input, self._check_task_skipped(t_input)))

        # validate dynamic func bodies before saving
        if not self._validate_dynamic_func_bodies(tasks, grid):
            logging.info('Save aborted due to unresolved syntax errors.')
            return

        # prepare loops
        loops = []
        itr = loop_property.GetPage(self.single_page).GetPyIterator(wx.propgrid.PG_ITERATE_ALL)

        for prop in itr:
            if isinstance(prop, wx.propgrid.PropertyCategory):
                continue

            loops.append(Loop(prop.GetName(), prop.GetValue()))

        execution_desc = self.v.execution_desc.GetValue() or ''
        as_tool = self.v.cb_astool.IsChecked()
        if len(tasks) > 0:
            Execution(name, tasks, execution_desc, as_tool, loops).save()

    def _check_task_skipped(self, input_json):
        try:
            if "skipped" not in input_json:
                return False

            data = json.loads(input_json)

            if "skipped" not in data:
                return False

            skipped_value = str(data["skipped"]).lower()

            return skipped_value in {"yes", "y", "true", "t"}

        except Exception as e:
            return False

    def _validate_dynamic_func_bodies(self, tasks, grid):
        """
        Validate syntax of dynamic function bodies in tasks before saving.
        If a syntax error is found, show an InputDialog for the user to edit and fix.
        Returns True if all valid (or user fixed all), False if user cancelled.
        """
        for task_idx, task in enumerate(tasks):
            task_number = task_idx + 1
            if not task.type or not hasattr(task, 'input') or not task.input:
                continue

            try:
                input_dict = json.loads(task.input)
            except (json.JSONDecodeError, TypeError):
                continue

            params_to_check = CodeExplainerUtil.get_dynamic_param_specs_with_source(task.type, input_dict)
            if not params_to_check:
                continue

            for param_name, func_args, body_prefix, spec_source in params_to_check:
                if param_name not in input_dict or not input_dict[param_name]:
                    continue

                if spec_source == 'fallback':
                    logging.warning(
                        f'Dynamic param inferred by naming convention @Task{task_number} '
                        f'[{task.type}] param="{param_name}". '
                        f'Consider adding explicit mapping in CodeExplainerUtil.DYNAMIC_FUNC_PARAMS.'
                    )

                raw_value = input_dict[param_name]
                if not isinstance(raw_value, str):
                    continue

                # Convert stored escape sequences to real characters for compilation
                func_body = raw_value.replace('\\n', '\n').replace('\\t', '\t')
                error = CodeExplainerUtil.validate_func_syntax(func_args, func_body, body_prefix)

                if error is None:
                    continue

                # Syntax error found — show InputDialog for editing
                while error is not None:
                    dlg = InputDialog(
                        self.v,
                        title=f"Syntax Error — Task {task_number} [{task.type}]",
                        message=f"Parameter: {param_name}\nError: {error}",
                        default_value=func_body
                    )

                    if dlg.ShowModal() == wx.ID_OK:
                        new_value = dlg.GetValue()
                        dlg.Destroy()

                        # Re-validate the edited code
                        error = CodeExplainerUtil.validate_func_syntax(func_args, new_value, body_prefix)
                        if error is None:
                            # User fixed it — store back with escape sequences
                            stored_value = new_value.replace('\n', '\\n').replace('\t', '\\t')
                            input_dict[param_name] = stored_value
                            task.input = json.dumps(input_dict)
                            grid.SetCellValue(task_idx, 1, task.input)
                            logging.info(
                                f'Task {task_number} [{task.type}] param "{param_name}" syntax fixed and updated.')
                        else:
                            # Still has error — loop to let user try again
                            func_body = new_value
                    else:
                        dlg.Destroy()
                        return False  # User cancelled — abort save

        return True

    def _save_pipeline(self, name):
        grid = self.v.executionGrid
        list = []

        for row in range(0, grid.GetNumberRows()):
            executionName = grid.GetCellValue(row, 0)
            executionInput = grid.GetCellValue(row, 1)
            if (len(executionName) == 0 and len(executionInput) == 0):
                break

            list.append({
                'execution': executionName,
                'input': executionInput
            })

        if (len(list) > 0):
            if self.v.asCronChecbox.IsChecked():
                if not self.CRON_INVALID == self.v.lableCronExplain.GetLabel():
                    Pipeline(name, list, self.v.asCronChecbox.IsChecked(), self.v.cronInput.GetValue()).save()
                else:
                    logging.warning('CRON is invalid, cron can not be saved')
            else:
                Pipeline(name, list).save()
        else:
            logging.warning('Execution list should NOT be empty')

    @reload_log_after
    def on_save_pipeline(self):
        combo = self.v.pipelineChooser
        name = combo.GetValue()

        if (len(name) == 0):
            logging.info(f'Pipeline: cron name should not be empty')
            return

        if combo.FindString(name) == -1:
            combo.Insert(name, 0)
        else:
            logging.warning(f'Pipeline: {combo.GetValue()} already existed, overwrite!')

        self._save_pipeline(name)

    @reload_log_after
    def on_save_execution(self):
        combo = self.v.executionChooser
        name = combo.GetValue()

        if combo.FindString(name) == -1:
            combo.Insert(name, 0)
        else:
            logging.warning(f'Execution: {combo.GetValue()} already existed, overrwrite!')

        self._save_execcution(name)

        # Sync tool icon prefix after save (astool may have changed)
        as_tool = self.v.cb_astool.IsChecked()
        tools = combo._tool_names
        if as_tool:
            tools = tools | {name}
        else:
            tools = tools - {name}
        combo.set_tool_names(tools)

    @reload_log_after
    def on_delete_pipeline(self):
        combo = self.v.pipelineChooser
        found = combo.FindString(combo.GetValue())

        if not found == -1:
            self.pipeline.delete()
            combo.Delete(found)

    @reload_log_after
    def on_delete_execution(self):
        combo = self.v.executionChooser
        found = combo.FindString(combo.GetValue())

        if not found == -1:
            self.execution.delete()
            combo.Delete(found)
            combo.SetValue('')

    @reload_log_after
    def on_stop_all(self):
        self.cron.stop_all()

    @reload_log_after
    def on_stop_current(self):
        if not self.pipeline is None:
            self.cron.stop_one(self.pipeline)

    @reload_log_after
    def on_run_pipeline(self):
        combo = self.v.pipelineChooser
        self.pipeline = Pipeline.get_pipeline(combo.GetValue())
        if self.v.asCronChecbox.IsChecked() and not self.CRON_INVALID == self.v.cronInput.GetValue():
            self.cron.add_one(self.pipeline)
        else:
            Thread(target=self.pipeline.run, args=({"__m": self.m, "__p": self}, self.v), daemon=True).start()

    @reload_log_after
    def on_run_execution(self, init_param: dict = None):
        combo = self.v.executionChooser
        self.execution = Execution.get_execution(combo.GetValue())

        # record last_run
        if self.m.last_run != combo.GetValue():
            self.m.last_run = combo.GetValue()
            self.m.set_config('last_run', self.m.last_run)

        fresh_init = dict(init_param) if init_param else {}
        fresh_init.update({"__m": self.m, "__p": self})
        executor = Executor(self.execution, fresh_init, self.v)
        self.executors.append(executor)
        executor.start()

    @reload_log_after
    def on_executeonstartup_changed(self, evt: wx.EVT_CHECKBOX):
        self.m.execute_on_startup = evt.IsChecked()
        self.m.set_config('execute_on_startup', self.m.execute_on_startup)

    @reload_log_after
    def on_stop_execution(self):
        for executor in self.executors:
            if executor.is_alive():
                executor.execution.set_should_be_stop(True)
                logging.info(f'Execution: [ {executor.execution.execution} ] is manually stopping.')

        self.executors = []

    @reload_log_after
    def on_select_recording(self):
        with wx.FileDialog(self.v, "Open Selenium IDE recording file", wildcard="recording files (*.side)|*.side",
                           style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST) as fileDialog:

            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return

            path_name = fileDialog.GetPath()
            self.v.recordingLocation.SetLabel(path_name)
            self.converter = SeleniumIDERecordingConverter(path_name)
            available_tests = self.converter.get_test_names()

            if len(available_tests) > 0:
                self.v.testChooser.Clear()
                self.v.testChooser.AppendItems(available_tests)

    @reload_log_after
    def on_recording_test_changed(self):
        self.converter.set_test_name(self.v.testChooser.GetValue())
        logging.info('load test: ' + self.v.testChooser.GetValue())

    @reload_log_after
    def on_load_from_recording(self):
        if hasattr(self, 'converter') and self.converter.is_initialized():
            tasks = self.converter.convert_from_selenium_ide_recording()

            task_grid = self.v.taskGrid
            selected_rows = task_grid.GetSelectedRows()
            tasks = tasks if len(selected_rows) > 0 else reversed(tasks)

            for t in tasks:
                selected_rows = task_grid.GetSelectedRows()
                insert_at = selected_rows[0] if len(selected_rows) > 0 else 0
                self._insert_row(task_grid, self.available_processors)
                task_grid.SetCellValue(insert_at, 0, t.type)
                if (hasattr(t, 'input')):
                    task_grid.SetCellValue(insert_at, 1, t.input)

            logging.info(
                f'Successfully convert from Selenium IDE recording: {self.converter.file_path}, {self.converter.test_name}')
        else:
            logging.warning(
                'Recording location and test name should not be empty, also able to select the row where start to load.')

    def _bind_grid_cell_choice_editor(self, rowAt, grid, choices):
        # Prefer searchable choice editor to improve UX when choice lists are long.
        try:
            grid.SetCellEditor(
                rowAt, 0,
                SearchableGridChoiceEditor(choices, allow_others=False, match_mode="contains")
            )
        except Exception:
            grid.SetCellEditor(
                rowAt, 0,
                wx.grid.GridCellChoiceEditor(choices, allowOthers=False)
            )
        # this cell editor is not working for mac so,
        if not OSUtils.get_system() == "darwin":
            grid.SetCellEditor(
                rowAt, 1,
                wx.grid.GridCellAutoWrapStringEditor()
            )

    def on_grid_cell_editor_shown4e(self, evt):
        current_row = evt.GetRow()
        current_column = evt.GetCol()
        evt.Skip()

    @reload_log_after
    def on_grid_cell_change4e(self, evt):
        grid = self.v.taskGrid
        current_value = grid.GetCellValue(evt.GetRow(), evt.GetCol())
        current_row = evt.GetRow()
        current_column = evt.GetCol()
        evt.Skip()

        if current_column == 0:
            if len(current_value) <= 0 or not current_value in self.available_processors:
                return
            p = Processor.get_processor_by_type(current_value)

            grid.SetCellValue(current_row, 1, p.get_tpl())

            logging.info(f'Processor {current_value} : {p.get_desc()}')
            self._load_input_taskproperty(current_row)

    @reload_log_after
    def on_grid_cell_select4e(self, evt):
        current_row = evt.GetRow()
        evt.Skip()
        self._load_input_taskproperty(current_row)

    def _load_input_taskproperty(self, current_row):
        grid = self.v.taskGrid
        self.current_selected_row = current_row
        self._pgrid_bound_row = current_row  # lock property grid to this row
        current_input = grid.GetCellValue(current_row, 1)
        if len(current_input) > 5:

            input_dict = json.loads(current_input)
            page = self.v.taskProperty.GetPage(self.single_page)
            self._reset_task_pgrid(current_row + 1)

            for k in input_dict:
                v = input_dict[k]
                self._append_or_update_property_to_page(k, v, page)

            page.FitColumns()

            current_processor = grid.GetCellValue(current_row, 0)
            self._fill_available_properties(current_processor, input_dict)
        else:
            self._reset_task_pgrid()
            self._pgrid_bound_row = -1  # no valid property binding

    def _fill_available_properties(self, processor, input_dict):
        self.v.avaibleProperties.Clear()
        tpl_dict = json.loads(Processor.get_processor_by_type(processor).get_tpl())
        available_processors = [k for k in tpl_dict.keys() if not k in input_dict]
        self.v.avaibleProperties.AppendItems(available_processors)

        # Sync the "skipped" checkbox to reflect the current task's skipped state.
        skipped_value = str(input_dict.get("skipped", "")).lower()
        is_skipped = skipped_value in {"yes", "y", "true", "t"}
        self.v.cb_skipped.SetValue(is_skipped)

    def _append_or_update_property_to_page(self, k, v, page):
        prop = page.GetPropertyByName(k)

        if prop is not None:
            prop.SetValue(v)
            return False

        if type(v) is str:
            page.Append(wx.propgrid.StringProperty(label=k, name=k, value=v))
        elif type(v) is int:
            page.Append(wx.propgrid.IntProperty(label=k, name=k, value=v))
        elif type(v) is list:
            page.Append(wx.propgrid.ArrayStringProperty(label=k, name=k, value=v))
        else:
            raise AttributeError('Unsupported property type:' + str(type(v)))
        page.FitColumns()
        return True

    def on_cron_actived(self, evt):
        self._update_cron_setting(1 == evt.Selection)

    def on_cron_changed(self):
        self._update_cron_setting(True)

    @reload_log_after
    def on_datepicker_changed(self, evt):
        date_str = evt.GetDate().Format("%Y-%m-%d")
        evt.Skip()
        tp = self.v.taskProperty
        prop = tp.GetSelection()
        if prop is not None:
            prop.SetValue(prop.GetValue() + date_str)
            self._modify_property(prop)

    def on_convert_get_data(self):
        self._convert('{self.get_data("")}')

    def on_convert_get_deep_data(self):
        self._convert('{self.get_deep_data(["",""])}')

    def on_append_date_str(self):
        self._convert('{self.get_now_str()}')

    def on_append_os_sep(self):
        self._convert('{os.sep}')

    def on_cb_astool_changed(self, evt):
        # When "as tool" is checked and the description field is empty,
        # pre-fill it with a default MCP tool descriptor template.
        combo = self.v.executionChooser
        name = combo.GetValue()
        if evt.IsChecked():
            current_desc = self.v.execution_desc.GetValue().strip()
            if not current_desc:
                default_desc = json.dumps(self._build_mcp_tool_template(name), indent=2, ensure_ascii=False)
                self.v.execution_desc.SetValue(default_desc)
        # Sync the tool icon prefix in the dropdown immediately
        combo.set_tool_names(
            combo._tool_names | {name} if evt.IsChecked()
            else combo._tool_names - {name}
        )

    @staticmethod
    def _build_mcp_tool_template(execution_name: str) -> dict:
        return {
            "desc": f"<Brief description of what {execution_name} does>",
            "inputSchema": {
                "type": "object",
                "title": f"{execution_name}Arguments",
                "properties": {
                    "param1": {
                        "title": "Param1",
                        "type": "string",
                        "description": "<describe param1>"
                    }
                },
                "required": [
                    "param1"
                ]
            },
            "outputSchema": {
                "type": "object",
                "title": f"{execution_name}Output",
                "properties": {
                    "result": {
                        "title": "Result",
                        "type": "string"
                    }
                },
                "required": [
                    "result"
                ]
            }
        }

    def _convert(self, to, put2first=False):
        tp = self.v.taskProperty
        prop = tp.GetSelection()
        if prop is None:
            return
        current_value = prop.GetValue()
        if put2first:
            prop.SetValue(to + current_value)
        else:
            prop.SetValue(current_value + to)
        self._modify_property(prop)

    @reload_log_after
    def on_convert_rdir(self):
        self._convert('{self.get_rdir()}/', True)

    @reload_log_after
    def on_convert_ddir(self):
        self._convert('{self.get_ddir()}/', True)

    @reload_log_after
    def on_convert_pwd(self):
        prefix = '{self.decrypt("'
        suffix = '")}'
        tp = self.v.taskProperty
        prop = tp.GetSelection()
        if prop is None:
            return

        current_value = prop.GetValue()

        if not type(current_value) is str:
            logging.info('please select a string property.')
            return

        if current_value.startswith(prefix) and current_value.endswith(suffix):
            current_value = current_value.replace(prefix, '')
            current_value = current_value.replace(suffix, '')
            prop.SetValue(Processor.decrypt_pwd(current_value))
        else:
            prop.SetValue(prefix + Processor.encrypt_pwd(current_value) + suffix)

        self._modify_property(prop)

    @reload_log_after
    def on_add_property(self):
        k = self.v.avaibleProperties.GetValue()

        if not len(k) > 0:
            return

        if self._pgrid_bound_row < 0:
            logging.info('No task row bound to property grid.')
            return

        grid = self.v.taskGrid
        processor = grid.GetCellValue(self._pgrid_bound_row, 0)
        tpl_dict = json.loads(Processor.get_processor_by_type(processor).get_tpl())

        if not k in tpl_dict:
            v = ''
        else:
            v = tpl_dict[k]

        self._append_or_update_property_to_page(k, v, self.v.taskProperty.GetPage(self.single_page))
        self._add_property(k, v)

        input_dict = json.loads(grid.GetCellValue(self._pgrid_bound_row, 1))
        self._fill_available_properties(processor, input_dict)

    @reload_log_after
    def on_skip_task_changed(self, evt):
        # Guard: a task row must be selected before toggling skip state
        if self.current_selected_row < 0:
            logging.info('Please select a task row first before toggling skip.')
            return

        page = self.v.taskProperty.GetPage(self.single_page)

        if evt.IsChecked():
            # Mark task as skipped: add/update 'skipped = yes' in both
            # the property grid panel and the backing task JSON in the grid cell
            self._append_or_update_property_to_page("skipped", "yes", page)
            self._add_property("skipped", "yes")
        else:
            # Un-skip: update 'skipped' to 'no' so the key stays visible
            # but is no longer treated as a skip signal by _check_task_skipped
            self._append_or_update_property_to_page("skipped", "no", page)
            self._add_property("skipped", "no")

    @reload_log_after
    def on_delete_property(self):
        tp = self.v.taskProperty
        prop = tp.GetSelection()
        if prop is None or isinstance(prop, wx.propgrid.PropertyCategory):
            logging.info('pls select property first.')
            return

        if self._pgrid_bound_row < 0:
            logging.info('No task row bound to property grid.')
            return

        self._delete_property(prop)
        self._delete_selected_property_from_page(tp)

        grid = self.v.taskGrid

        input_dict = json.loads(grid.GetCellValue(self._pgrid_bound_row, 1))
        processor = grid.GetCellValue(self._pgrid_bound_row, 0)
        self._fill_available_properties(processor, input_dict)

    def _delete_selected_property_from_page(self, pgm):
        prop = pgm.GetSelection()
        if prop is None or isinstance(prop, wx.propgrid.PropertyCategory):
            logging.info('pls select value property first.')
            return
        pgm.DeleteProperty(prop.GetName())

    @reload_log_after
    def _update_cron_setting(self, enabled: bool):
        if enabled:
            self.v.lableCronExplain.SetLabel(self._explain_cron(self.v.cronInput.GetValue()))
            self.v.cronInput.Enable(True)
        else:
            self.v.lableCronExplain.SetLabel("")
            self.v.cronInput.Enable(False)

    def _explain_cron(self, cron):
        try:
            return str(ExpressionDescriptor(cron))
        except Exception as e:
            logging.error(f"{self.CRON_INVALID}: [ " + cron + " ] just try [ 0 * * * * ]")
            return self.CRON_INVALID

    @reload_log_after
    def on_property_change4e(self, evt):
        prop = evt.GetProperty()
        evt.Skip()
        self._modify_property(prop)

    def on_property_right_click4e(self, evt):
        prop = evt.GetProperty()
        evt.Skip()
        if prop is None or isinstance(prop, wx.propgrid.PropertyCategory):
            return

        self._right_clicked_property = prop

        menu = wx.Menu()
        id_copy_name = wx.NewId()
        id_copy_value = wx.NewId()
        id_edit_complex = wx.NewId()

        menu.Append(id_copy_name, "Copy Name")
        menu.Append(id_copy_value, "Copy Value")
        menu.AppendSeparator()
        menu.Append(id_edit_complex, "Edit Complex Value")

        self.v.Bind(wx.EVT_MENU, self._on_copy_property_name, id=id_copy_name)
        self.v.Bind(wx.EVT_MENU, self._on_copy_property_value, id=id_copy_value)
        self.v.Bind(wx.EVT_MENU, self._on_edit_complex_value, id=id_edit_complex)

        self.v.PopupMenu(menu)
        menu.Destroy()

    def _on_copy_property_name(self, evt):
        if self._right_clicked_property is not None:
            name = self._right_clicked_property.GetName()
            if wx.TheClipboard.Open():
                wx.TheClipboard.SetData(wx.TextDataObject(str(name)))
                wx.TheClipboard.Close()
                logging.info(f'Copied property name to clipboard: {name}')

    def _on_copy_property_value(self, evt):
        if self._right_clicked_property is not None:
            value = self._right_clicked_property.GetValue()
            if wx.TheClipboard.Open():
                wx.TheClipboard.SetData(wx.TextDataObject(str(value)))
                wx.TheClipboard.Close()
                logging.info(f'Copied property value to clipboard: {value}')

    @reload_log_after
    def _on_edit_complex_value(self, evt):
        prop = self._right_clicked_property
        if prop is None:
            return

        prop_name = prop.GetName()
        raw_value = prop.GetValue()

        if isinstance(raw_value, str):
            display_value = raw_value.replace('\\n', '\n').replace('\\t', '\t')
        else:
            display_value = str(raw_value)

        task_number = (self._pgrid_bound_row or 0) + 1
        dlg = InputDialog(self.v, title=f"Edit Complex Value - Task {task_number}",
                          message=f"Property: {prop_name}",
                          default_value=display_value)

        if dlg.ShowModal() == wx.ID_OK:
            new_value = dlg.GetValue()
            stored_value = new_value.replace('\n', '\\n').replace('\t', '\\t')
            prop.SetValue(stored_value)
            self._modify_property(prop)

        dlg.Destroy()

    def _add_property(self, propName, propValue):
        self._op_taskgrid_property(propName, propValue, lambda inputDict, key, value: inputDict | {key: value})
        logging.info(f'Input property added @Task{self._pgrid_bound_row + 1} - [ {propName} = {propValue} ]')

    def _delete_property(self, prop):
        self._op_taskgrid_property(prop.GetName(), prop.GetValue(),
                                   lambda inputDict, key, value: {k: v for k, v in inputDict.items() if not k == key})
        logging.info(f'Input property deleted @Task{self._pgrid_bound_row + 1} - [ {prop.GetName()} ]')

    def _modify_property(self, prop):
        self._op_taskgrid_property(prop.GetName(), prop.GetValue(),
                                   lambda inputDict, key, value: inputDict | {key: value})
        logging.info(
            f'Input property modified @Task{self._pgrid_bound_row + 1} - [ {prop.GetName()} = {prop.GetValue()} ]')

    def _op_taskgrid_property(self, key, value, func):
        task_grid = self.v.taskGrid
        input_col = 1

        # Use the row the property grid was populated for, NOT the
        # currently selected grid row — they can differ when the user
        # clicks a new row while a property editor is still open.
        target_row = self._pgrid_bound_row

        if target_row is None or target_row < 0 or key is None or value is None:
            return

        if target_row != self.current_selected_row:
            logging.warning(
                f'Property grid bound to row {target_row} but grid selection is at row '
                f'{self.current_selected_row} — writing to row {target_row} (property grid source).')

        input = task_grid.GetCellValue(target_row, input_col)
        input_dict = json.loads(input)
        input_dict = func(input_dict, key, value)
        input = json.dumps(input_dict)
        task_grid.SetCellValue(target_row, input_col, input)

    def on_grid_cell_change4p(self, evt):
        grid = self.v.executionGrid
        current_row = evt.GetRow()
        current_column = evt.GetCol()
        evt.Skip()

    def _insert_row(self, grid, choices):
        selected_rows = grid.GetSelectedRows()
        total_rows = grid.GetNumberRows()
        insert_at_row = selected_rows[0] if len(selected_rows) > 0 else 0

        # if select on last row, then append.
        if insert_at_row + 1 == total_rows:
            insert_at_row = total_rows

        grid.InsertRows(insert_at_row, 1, True)
        self._bind_grid_cell_choice_editor(insert_at_row, grid, choices)

    def on_add_row4e(self):
        task_grid = self.v.taskGrid
        self._insert_row(task_grid, self.available_processors)

    def on_add_row4p(self):
        execution_grid = self.v.executionGrid
        self._insert_row(execution_grid, self.available_executions)

    def on_delete_rows4e(self):
        self._on_delete_rows(self.v.taskGrid)

    def on_delete_rows4p(self):
        self._on_delete_rows(self.v.executionGrid)

    def _on_delete_rows(self, grid):
        total_row = grid.GetNumberRows()
        if total_row > 0:
            rows_be_deleted = grid.GetSelectedRows()
            last_row_at = total_row - 1
            deleteStartRow = rows_be_deleted[0] if len(rows_be_deleted) > 0 else last_row_at
            deleteNumber = len(rows_be_deleted) if len(rows_be_deleted) > 0 else 1
            grid.DeleteRows(pos=deleteStartRow, numRows=deleteNumber, updateLabels=True)

    def on_load_log_async(self):
        """Throttled async log reload — skip if called too frequently."""
        now = time.monotonic()
        if now - self._log_last_update < self._log_throttle_sec:
            if not self._log_pending:
                self._log_pending = True
                delay_ms = int(self._log_throttle_sec * 1000)
                wx.CallLater(delay_ms, self._deferred_load_log)
            return
        with concurrent.futures.ThreadPoolExecutor() as executor:
            executor.submit(self.on_load_log)

    def _deferred_load_log(self):
        """Fires after throttle window expires."""
        self._log_pending = False
        with concurrent.futures.ThreadPoolExecutor() as executor:
            executor.submit(self.on_load_log)

    def on_load_log(self):
        if hasattr(self, 'isLoading') and self.isLoading:
            return

        if self.is_log_content_focused:
            return

        log_path = OSUtils.get_log_file_path(self.m.app_name)

        try:
            self.isLoading = True
            file_size = os.path.getsize(log_path)
            max_size = 5 * 1024 * 1024  # 5MB

            # File was truncated / rotated (e.g. after "Clean") → full reload
            if file_size < self._log_last_pos:
                self._log_last_pos = 0

            if self._log_last_pos == 0:
                # --- Full load (initial or after clean) ---
                with open(log_path, 'r', encoding='utf8', errors='replace') as f:
                    if file_size > max_size:
                        truncate_message = f"[log is too big, only showing last {max_size / 1024 / 1024:.1f}MB.]\n\n"
                        f.seek(file_size - max_size)
                        f.readline()  # skip partial line
                        content = truncate_message + f.read()
                    else:
                        content = f.read()
                    self._log_last_pos = f.tell()
                wx.CallAfter(self._full_update_log, content)
            else:
                # --- Incremental append (the fast path) ---
                with open(log_path, 'r', encoding='utf8', errors='replace') as f:
                    f.seek(self._log_last_pos)
                    new_content = f.read()
                    self._log_last_pos = f.tell()

                if new_content:
                    wx.CallAfter(self._append_log, new_content, max_size)

            self._log_last_update = time.monotonic()
        except Exception as e:
            logging.error(f"Fail to load log: {str(e)}")
        finally:
            self.isLoading = False

    def _full_update_log(self, content):
        """Full replacement — used only on first load or after clean."""
        try:
            self.v.logContents.Freeze()
            self.v.logContents.SetValue(content)
            self.v.logContents.ShowPosition(self.v.logContents.GetLastPosition())
        except Exception as e:
            logging.error(f"Update log error from UI: {str(e)}")
        finally:
            self.v.logContents.Thaw()

    def _append_log(self, new_content, max_size):
        """Incremental append — much faster than full SetValue."""
        try:
            self.v.logContents.Freeze()

            # Trim from the front if total would exceed limit
            current_len = self.v.logContents.GetLastPosition()
            if current_len + len(new_content) > max_size:
                trim_amount = (current_len + len(new_content)) - max_size
                self.v.logContents.Remove(0, trim_amount)

            self.v.logContents.AppendText(new_content)
        except Exception as e:
            logging.error(f"Append log error from UI: {str(e)}")
        finally:
            self.v.logContents.Thaw()

    @reload_log_after
    def on_clean_log(self):
        with open(OSUtils.get_log_file_path(self.m.app_name), 'w', encoding='utf8') as file:
            file.write(f'Clean {self.m.app_name} log@' + DateUtil.get_now_in_str() + '\n')
        self.is_log_content_focused = False
        self._log_last_pos = 0  # reset so next reload does a full load

    def on_logcontents_focused(self):
        self.is_log_content_focused = True

    def on_logcontents_unfocused(self):
        self.is_log_content_focused = False

    def on_handle_display_in_matplotlib_view(self, evt: PETPEvent):
        data = evt.data

        if data['chart_type'] == 'PIE':
            PETP_PIE_CHARTView(self.v, wx.ID_ANY, data=data).Show()
        elif data['chart_type'] == 'BAR':
            PETP_BAR_CHARTView(self.v, wx.ID_ANY, data=data).Show()
        elif data['chart_type'] == 'LINE':
            PETP_LINE_CHARTView(self.v, wx.ID_ANY, data=data).Show()
        else:
            logging.warning(f'Unsupported chart type: {data["chart_type"]}')

    def on_handle_open_input_dialog(self, evt: PETPEvent):
        advance_dialog = InputDialog(self.v, evt.data['title'], evt.data['msg'], evt.data['default_value'])
        result_value = None

        if advance_dialog.ShowModal() == wx.ID_OK:
            result_value = advance_dialog.GetValue()

        advance_dialog.Destroy()

        if evt.handler:
            evt.handler(result_value)

    @reload_log_after
    def on_handle_http_request(self, evt: PETPEvent):
        action = evt.data['action']

        if action == 'execution':
            params = evt.data['params']
            exection_name = params['execution']
            execution: Execution = Execution.get_execution(params['execution'])

            if hasattr(execution, 'astool') and execution.astool:
                self.v.executionChooser.SetValue(exection_name)
                self.on_task_execution_changed()
                self.on_run_execution(params)
            else:
                from httpservice.handlers.HttpRequestHandler import HttpRequestHandler
                request_id_key = HttpRequestHandler.get_request_id_key()
                request_id = params.get(request_id_key)
                server = HttpRequestHandler.get_server()
                if request_id and server:
                    server.store_result(request_id, {"error": f"Execution '{exection_name}' is not available as a tool (astool=false)"})
        logging.info(f'\nHTTP request be handled - action: {action}, params: {params}\n')

    def get_tools(self):
        tools = {}
        for execution_name in self.available_executions:
            execution = Execution.get_execution(execution_name)
            if (hasattr(execution, 'astool') and execution.astool
                    and hasattr(execution, 'mcp_desc') and execution.mcp_desc):
                tools[execution_name] = execution.mcp_desc
        return tools
