!!python/object:core.execution.Execution
astool: false
execution: SAP_CPI_EXTRACTOR_CONFIG
list:
- !!python/object:core.task.Task
  input: '{"SCPI_Host": "e350056-tmn.hci.ca1.hana.ondemand.com", "user": "I335607",
    "password": "{self.decrypt(\"e77h9j3HZhnWQX2sopZ/dsYKFkPF7A==*EZwFmMlLv1KXgPHZ1RFTmQ==*KFS6jNCTpSHb0yuoRHBLFQ==*Ytbw4DqJySim27EX/mdpSw==\")}",
    "filename": "{self.get_ddir()}/config_runtime.json", "mode": "runtime", "mode_desc":
    "designtime | runtime | designtime", "url_list_command": "https://{SCPI_Host}/itspaces/Operations/com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentsListCommand",
    "url_artifact_prefix": "https://{SCPI_Host}/api/v1/IntegrationDesigntimeArtifacts(Id=''",
    "basicAuth": "{user}:{password}", "url_artifact_suffix": "'',Version=''active'')/$value"}'
  skipped: false
  type: INITIAL_PARAMS
- !!python/object:core.task.Task
  input: '{"type": "ENCODE", "inbound": "{basicAuth}", "outbound_key": "basicAuth",
    "algorithms": "base64"}'
  skipped: false
  type: ENCODE_DECODE_STR
- !!python/object:core.task.Task
  input: '{"request_url":"{url_list_command}","method":"get","value_key":"resp","timeout":60,"headers":"Authorization[>Basic {basicAuth}|>ACCEPT[>application/json","resp_fn":"return response.text if response.status_code == 200 else response.status_code"}'
  skipped: false
  type: HTTP_REQUEST
- !!python/object:core.task.Task
  input: '{"title": "HTTP\u670d\u52a1\u7aef\u8fd4\u56de", "msg": "{resp}"}'
  skipped: false
  type: SHOW_RESULT
- !!python/object:core.task.Task
  input: '{"given_key": "resp", "target_key": "artifactInformations", "convertor_func":
    "return p.json2dict(given)[''artifactInformations'']"}'
  skipped: false
  type: DATA_CONVERT
- !!python/object:core.task.Task
  input: '{"source_key":"artifactInformations","target_key":"","filter_fn":" ''VALUE_MAPPING'' != row[''type'']"}'
  skipped: false
  type: DATA_FILTER
- !!python/object:core.task.Task
  input: '{"start_idx":"","end_idx":"","source_key":"artifactInformations","target_key":"iflow_id_arr","map_fn":"[item[''id''], item[''name''], item[''symbolicName'']]"}'
  skipped: false
  type: DATA_MAPPING
- !!python/object:core.task.Task
  input: '{"title": "found {len(iflow_id_arr)} items", "msg": "{json.dumps(iflow_id_arr)}",
    "skipped": "yes"}'
  skipped: true
  type: SHOW_RESULT
- !!python/object:core.task.Task
  input: '{"request_url":"{url_artifact_prefix}{loop_item[2]}{url_artifact_suffix}","method":"get","value_key":"artifact_resp","timeout":60,"headers":"Authorization[>Basic {basicAuth}|>ACCEPT[>application/json","is_zip_response":"yes","filter_fn":"return filename.endswith(''parameters.prop'') or filename.endswith(''.iflw'')","convert_fn":"return file_content.decode(''utf-8'')"}'
  skipped: false
  type: HTTP_REQUEST
- !!python/object:core.task.Task
  input: '{"title": "Get Artifact : {loop_item[2]}", "msg": "{json.dumps(artifact_resp)}",
    "skipped": "yes"}'
  skipped: true
  type: SHOW_RESULT
- !!python/object:core.task.Task
  input: '{"given_key": "artifact_resp", "target_key": "artifact_resp_prop", "convertor_func":
    "return p.prop2dict(next(v for k, v in given.items() if k.endswith(''.prop'')))"}'
  skipped: false
  type: DATA_CONVERT
- !!python/object:core.task.Task
  input: '{"inbound_data_key": "", "inbound_data": "{next(v for k, v in artifact_resp.items()
    if k.endswith(''.iflw''))}", "parser": "xml", "outbound_data_key": "soup_outbound",
    "func_body": "    al=[]\\n\\n    collaboration = soup.find(\"collaboration\")\\n    if
    not collaboration:\\n        return al\\n\\n    prop = p.get_data(''artifact_resp_prop'')\\n\\n    for
    mf in collaboration.find_all(\"messageFlow\"):\\n        row = {\"IFlow\": p.get_data(''loop_item'')[2]}\\n\\n        for
    pro in mf.find_all(\"property\"):\\n            key_tag = pro.find(\"key\")\\n            val_tag
    = pro.find(\"value\")\\n\\n            key = key_tag.get_text() if key_tag else
    \"\"\\n            value = val_tag.get_text() if val_tag else \"\"\\n\\n            if
    \"{{\" in value:\\n                value = p.feed_tpl(value, prop)\\n\\n            row[key]
    = value\\n\\n        al.append(row)\\n    return al"}'
  skipped: false
  type: BEAUTIFUL_SOUP
- !!python/object:core.task.Task
  input: '{"title": "Get Artifact : {loop_item[2]}", "msg": "{json.dumps(soup_outbound)}",
    "skipped": "yes"}'
  skipped: true
  type: SHOW_RESULT
- !!python/object:core.task.Task
  input: '{"target":"iflow_obj_list","type":"list","list_row_lambda":"me.get_data(''soup_outbound'')","list_flatten":"yes","clean_before_collect":"no"}'
  skipped: false
  type: DATA_COLLECT
- !!python/object:core.task.Task
  input: '{"wait_seconds":"5"}'
  skipped: false
  type: WAIT_SECONDS
- !!python/object:core.task.Task
  input: '{"name":"reload logger"}'
  skipped: false
  type: RELOAD_LOG
- !!python/object:core.task.Task
  input: '{"title": "Collect iflow Object - {len(iflow_obj_list)}", "msg": "{json.dumps(iflow_obj_list)}"}'
  skipped: false
  type: SHOW_RESULT
loops:
- !!python/object:core.loop.Loop
  loop_attributes: '{"task_start":9, "task_end":16, "loop_key":"iflow_id_arr", "loop_times":"0",
    "loop_index_key":"loop_idx", "item_key":"loop_item", "exception_then":"continue"}'
  loop_code: loop-20260414230025
mcp_desc: ''
