!!python/object:core.execution.Execution
astool: false
execution: SAP_CPI_COMPARE_THEN_CONFIG
list:
- !!python/object:core.task.Task
  input: '{"SCPI_Host_s": "l350122-tmn.hci.ca1.hana.ondemand.com", "user_s": "I335607",
    "password_s": "{self.decrypt(\"e77h9j3HZhnWQX2sopZ/dsYKFkPF7A==*EZwFmMlLv1KXgPHZ1RFTmQ==*KFS6jNCTpSHb0yuoRHBLFQ==*Ytbw4DqJySim27EX/mdpSw==\")}",
    "url_list_command_s": "https://{SCPI_Host_s}/itspaces/Operations/com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentsListCommand",
    "SCPI_Host_t": "e350056-tmn.hci.ca1.hana.ondemand.com", "user_t": "I335607", "password_t":
    "{self.decrypt(\"e77h9j3HZhnWQX2sopZ/dsYKFkPF7A==*EZwFmMlLv1KXgPHZ1RFTmQ==*KFS6jNCTpSHb0yuoRHBLFQ==*Ytbw4DqJySim27EX/mdpSw==\")}",
    "url_list_command_t": "https://{SCPI_Host_t}/itspaces/Operations/com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentsListCommand",
    "url_artifact_suffix": "'',Version=''active'')/$value"}'
  skipped: false
  type: INITIAL_PARAMS
- !!python/object:core.task.Task
  input: '{"request_url":"{url_list_command_s}","method":"get","value_key":"resp_s","timeout":60,"headers":"ACCEPT[>application/json","basic_auth_user":"{user_s}","basic_auth_pwd":"{password_s}","resp_fn":"return response.text if response.status_code == 200 else response.status_code"}'
  skipped: false
  type: HTTP_REQUEST
- !!python/object:core.task.Task
  input: '{"request_url":"{url_list_command_t}","method":"get","value_key":"resp_t","timeout":60,"headers":"ACCEPT[>application/json","basic_auth_user":"{user_t}","basic_auth_pwd":"{password_t}","resp_fn":"return response.text if response.status_code == 200 else response.status_code"}'
  skipped: false
  type: HTTP_REQUEST
- !!python/object:core.task.Task
  input: '{"title": "HTTP\u670d\u52a1\u7aef\u8fd4\u56de_S", "msg": "{resp_s}"}'
  skipped: false
  type: SHOW_RESULT
- !!python/object:core.task.Task
  input: '{"title": "HTTP\u670d\u52a1\u7aef\u8fd4\u56de_T", "msg": "{resp_t}"}'
  skipped: false
  type: SHOW_RESULT
loops: []
mcp_desc: ''
