application:
  app_name: petp
  author: sunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  enable_windows_hdpi: false
  execute_on_startup: false
  http_port: 8866
  http_request_timeout: 600
  http_request_token: cGV0cDpzdW5qdW5iaW46ODYxMzQ3ODY1MzMyMzo2MDk5MDEyQHFxLmNvbQ==
  language: zh
  last_run: loop_time
  log_level: INFO
  nogui_enabled: true
  nogui_ui_processor_policy: skip
  snapshot_max: 20
  version: 1.2.0
