application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  enable_windows_hdpi: false
  execute_on_startup: false
  http_port: 8866
  http_request_timeout: 60 #seconds
  last_run: test_read_from_excel
  log_level: INFO
  version: 1.0.5
