application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  enable_windows_hdpi: false
  execute_on_startup: false
  http_port: 8866
  http_request_timeout: 60
  http_request_token: cGV0cDpzdW5qdW5iaW46ODYxMzQ3ODY1MzMyMzo2MDk5MDEyQHFxLmNvbQ==
  last_run: OOTB_BS4_GET_DATA_FROM_news.ceic.ac.cn
  log_level: INFO
  version: 1.1.0
