###
GET {{baseURL}}

###
POST  {{baseURL}}
Content-Type: application/json

{
  "generated-in": "PyCharm",
  "message": "Hello, World!"
}

###
POST  {{baseURL}}petp
Content-Type: application/json

{
  "action": "execution",
  "params": {
    "execution": "test_DB_ACCESS_Sqlite",
    "user": "sunjunbin",
    "table": "user"
  }
}

###
POST  {{baseURL}}petp
Content-Type: application/json

{
    "action": "execution",
    "params":{
        "execution":"test_read_from_excel",
        "fromHTTPservice":true
    }
}